#!/bin/sh

PATCHFILE=$(readlink -f patchfile)
SV_DIR=$1

if [ "$SV_DIR" = "" ]; then
    echo "sv-comp directory path not supplied! Trying if we share the same parent directory."
    cd ..

    if [ ! -d sv-benchmarks ]; then
        echo "sv-benchmarks directory not found!"
        exit 2
    else
        echo "sv-benchmarks directory found, proceeding…"
        SV_DIR=sv-benchmarks/c
    fi
else
    if [ ! -d "$SV_DIR/c/" ]; then
        echo "Invalid directory $SV_DIR"
        exit 1
    fi
    SV_DIR="$SV_DIR/c"
fi
cd "$SV_DIR"

git apply --check "$PATCHFILE" || { echo "SV-Comp makefile already modified! Aborting. Maybe the patch is already applied?"; exit; }
git apply "$PATCHFILE" && echo "Succesfully patched the makefile for use with vast-front"
